version: '3.1'

# docker-compose.yaml
# rigveda app
# author devb
# modified: 11/5/20

services:

  # app
  rigveda:
    build: .
    ports:
      - "8087:5000"
    volumes:
      - .:/rigveda
    environment:
      FLASK_ENV: development
    networks:
      - rv

  # database
  mongodb_container:
    image: localhost:5000/mongo:dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - rv

# volume
volumes:
  mongodb_data_container:

# docker networks
networks:
  rv:
    driver: bridge

